name: Deploy Code to Release Branch
on:
  workflow_dispatch:

jobs:
  build:
    name: Push to Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.0'

      - name: Install
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: rafaelarojas/git-pages-deploy-action@v4
        with:
          folder: build
          branch: main
